# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=20, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(default='register', max_length=20, unique=(('register', '用户注册'), ('forget', '找回密码')), verbose_name='类型'),
        ),
    ]
