# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171227_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '用户注册'), ('forget', '找回密码')], default='register', max_length=20, verbose_name='类型'),
        ),
    ]
