# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171227_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Banner/%Y/%m', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '用户注册'), ('forget', '找回密码')], default='register', max_length=20, verbose_name='验证码类型'),
        ),
    ]
