# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailverifyrecord_is_sx'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverifyrecord',
            table=None,
        ),
    ]
