# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171229_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_jh',
            field=models.IntegerField(blank=True, choices=[('1', '激活'), ('0', '未激活')], default='1', null=True, verbose_name='是否激活'),
        ),
    ]
