# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180104_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_jh',
            field=models.CharField(blank=True, choices=[('1', '激活'), ('0', '未激活')], default='1', max_length=10, null=True, verbose_name='是否激活'),
        ),
    ]
