# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180104_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '用户注册'), ('forget', '找回密码'), ('upload_email', '修改密码')], default='register', max_length=20, verbose_name='验证码类型'),
        ),
    ]
