# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180104_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='is_sx',
            field=models.CharField(choices=[('1', '可用'), ('0', '不可用')], default='1', max_length=5, verbose_name='激活是否可以'),
        ),
    ]
