# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180104_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='is_sx',
            field=models.BooleanField(choices=[('1', '可用'), ('0', '不可用')], default='1', verbose_name='激活是否可以'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_jh',
            field=models.BooleanField(choices=[('1', '激活'), ('0', '未激活')], default='1', verbose_name='是否激活'),
        ),
    ]
