# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='kcs',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='lxfs',
            field=models.CharField(default='010-00000000', max_length=20, verbose_name='联系电话'),
        ),
    ]
