# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_xxrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='js/%Y/%m', verbose_name='教师图片'),
        ),
    ]
