# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180103_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_arg',
            field=models.IntegerField(default=20, verbose_name='讲师年龄'),
        ),
    ]
