# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180103_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='org_tag',
            field=models.CharField(default='全国知名', max_length=4, verbose_name='机构类型'),
        ),
    ]
