# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coures_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='封面图片'),
        ),
    ]
