# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
        ('courses', '0004_auto_20171231_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='coures',
            name='kcjs_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程讲师'),
        ),
    ]
