# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coures_kcjs_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='coures',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课程类别'),
        ),
        migrations.AlterField(
            model_name='coures',
            name='degree',
            field=models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], default='zj', max_length=5, verbose_name='视频级别'),
        ),
    ]
