# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180101_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='视频资源地址'),
        ),
    ]
