# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='视频时长'),
        ),
    ]
