# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_video_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coures',
            name='kcxz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='coures',
            name='xdaoshenm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='能学到什么？'),
        ),
    ]
