# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 00:30
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coures_is_tg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCoures',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.coures',),
        ),
        migrations.AlterField(
            model_name='coures',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情'),
        ),
    ]
